[[section-architecture-constraints]]
== Randbedingungen

Dieses Kapitel beleuchtet alles, was das Team beim Design und der Implementierung der Architektur
einschränkt. Diese Einschränkungen sind manchmal auch außerhalb eines Projekts in der gesamten Organisation gültig.

Der Inhalt des Kapitels sollte nach arc42 Empfehlung jede Anforderung sein, die Softwarearchitekten in ihrer Freiheit bei Design- und Implementierungsentscheidungen oder Entscheidungen über den Entwicklungsprozess einschränkt. Diese Zwänge gehen manchmal über einzelne Systeme hinaus und gelten für ganze Organisationen und Unternehmen.

Die Motivation hinter diesem Kapitel liegt darin, dass Architekten genau wissen sollten, wo sie in ihren Designentscheidungen frei sind und wo sie sich an Einschränkungen halten müssen. Zwänge müssen immer beachtet werden; sie können jedoch verhandelbar sein.

Die empfohlene Form sind einfache Tabellen mit Einschränkungen und Erklärungen. Bei Bedarf können diese unterteilt werden in technische Randbedingungen, organisatorische und politische Randbedingungen und Konventionen (z.B. Programmier- oder Versionierungsrichtlinien, Dokumentations- oder Namenskonventionen). 


=== Technische Randbedingungen

Dieser Abschnitt soll nachvollziehbar die Fragestellung klären: Was sind die techn. Randbedingungen (hinsichtlich der Architektur)?

[options="header"]
|===
|Techn. Randbedingung | Beschreibung 

|<Text> |<Text>

|<Text> |<Text> 

|===


=== Organisatorische Randbedingungen

Dieser Abschnitt erläutert die Fragestellung: Was sind die organisatorischen Randbedingungen?

Hier erfolgt eventuell ein Verweis auf die Stakeholder aus Kapitel 1 hinsichtlich der organisatorischen Randbedingungen.

[options="header"]
|===
|Organ. Randbedingung | Beschreibung 

|<Text> |<Text>

|<Text> |<Text> 

|===

=== Konventionen

Dieser Abschnitt behandelt und politische Randbedingungen und Konventionen (z.B. Programmier- oder Versionierungsrichtlinien, Dokumentations- oder Namenskonventionen) im Kontext von dqualizer. Er soll die Frage "Was sind (weitere) Konventionen, welche beachtet werden sollen oder müssen?" beantworten. 

[options="header"]
|===
|Konvention | Beschreibung 

|<Text> | Die Dokumentation der Architektur orientiert sich soweit sinnvoll an dem arc42 Template 

|<Text> |<Text> 

|===
