[[section-runtime-view]]
== Laufzeitsicht

Die Laufzeitsicht beschreibt das konkrete Verhalten und die Interaktionen der Systembausteine in Form von Szenarien aus den folgenden Bereichen:

   * wichtige Anwendungsfälle oder Funktionen: wie werden sie von den Bausteinen ausgeführt?
    * Interaktionen an kritischen externen Schnittstellen: Wie arbeiten die Bausteine mit Benutzern und Nachbarsystemen zusammen?
   * Betrieb und Verwaltung: Start, Inbetriebnahme, Stopp
   * Fehler- und Ausnahmeszenarien

Es sei zu beachten, dass das Hauptkriterium für die Auswahl der möglichen Szenarien (Sequenzen, Workflows) ist ihre architektonische Relevanz. Es ist nicht wichtig, eine große Anzahl von Szenarien zu beschreiben. Sie sollten vielmehr eine repräsentative Auswahl dokumentieren.

=== _<Bezeichnung Laufzeitszenario 1>_

* <hier Laufzeitdiagramm oder Ablaufbeschreibung einfügen>
* <hier Besonderheiten bei dem Zusammenspiel der Bausteine in diesem Szenario erläutern>

Siehe Miro Board -> unter Bausteinsicht Ebene 1 Iteration 2 -> Laufzeitsicht -> in PlantUML

=== _<Bezeichnung Laufzeitszenario 2>_

...

=== _<Bezeichnung Laufzeitszenario n>_

...
