[[section-deployment-view]]
== Verteilungssicht (Deployment View)

In diesem Kapitel wird die technische Infrastruktur mit (echten oder virtuellen) Prozessoren, Systemtopologie, und die Abbildung der Software-Bausteine auf diese Infrastruktur beleuchtet.

Die Verteilungssicht beschreibt:

* die technische Infrastruktur, die zur Ausführung Ihres Systems verwendet wird, mit Infrastrukturelementen wie geografischen Standorten, Umgebungen, Computern, Prozessoren, Kanälen und Netz-Topologien sowie anderen Infrastrukturelementen und
* die Zuordnung von (Software-)Bausteinen zu diesen Infrastrukturelementen.

Oft werden Systeme in verschiedenen Umgebungen ausgeführt, z. B. Entwicklungsumgebung, Testumgebung, Produktionsumgebung. In solchen Fällen sollten Sie alle relevanten Umgebungen dokumentieren.

Dokumentieren Sie insbesondere die Deployment-Sicht, wenn Ihre Software als verteiltes System mit mehreren Computern, Prozessoren, Servern oder Containern ausgeführt wird oder wenn Sie Ihre eigenen Hardware-Prozessoren und Chips entwerfen und konstruieren.

Aus der Software-Perspektive reicht es aus, die Elemente der Infrastruktur zu erfassen, die erforderlich sind, um den Einsatz Ihrer Bausteine darzustellen. Hardware-Architekten können darüber hinausgehen und die Infrastruktur bis zu einem beliebigen Detaillierungsgrad beschreiben, den sie benötigen.

Motivation: Software läuft nicht ohne Hardware. Die zugrunde liegende Infrastruktur kann und wird Ihr System und/oder einige übergreifende Konzepte beeinflussen. Daher müssen Sie die Infrastruktur kennen.

Form: Das Deployment-Diagramm auf höchster Ebene ist vielleicht schon in Abschnitt 3.2. als technischer Kontext mit Ihrer eigenen Infrastruktur als EINE Blackbox enthalten. In diesem Abschnitt werden Sie in diese Blackbox hineinzoomen, indem Sie zusätzliche Deployment-Diagramme verwenden.

* Die UML bietet Deployment-Diagramme, um diese Sichtweise auszudrücken. Verwenden Sie diese, wahrscheinlich mit verschachtelten Diagrammen, wenn Ihre Infrastruktur komplexer ist.
* Wenn Ihre (Hardware-)Stakeholder andere Diagrammtypen als UML-Deployment-Diagramme bevorzugen, lassen Sie sie jede Art von Diagramm verwenden, das die Knoten und Kanäle der Infrastruktur darstellen kann.

=== Infrastruktur Ebene 1

Beschreiben Sie (normalerweise in einer Kombination aus Diagrammen, Tabellen und Text):

* die Verteilung Ihres Systems auf mehrere Standorte, Umgebungen, Computer, Prozessoren, ... sowie die physischen Verbindungen zwischen ihnen
* eine wichtige Begründung oder Motivation für diese Einsatzstruktur
* Qualitäts- und/oder Leistungsmerkmale der Infrastruktur
* die Zuordnung von Software-Artefakten (Bausteinen) zu Elementen der Infrastruktur

_**<Übersichtsdiagramm>**_

Begründung:: _<Erläuternder Text>_

Qualitäts- und/oder Leistungsmerkmale:: _<Erläuternder Text>_

Zuordnung von Bausteinen zu Infrastruktur:: _<Beschreibung der Zuordnung>_

=== Infrastruktur Ebene 2

Hier können Sie die interne Struktur von (einigen) Infrastrukturelementen der Infrastrukturebene 1 übernehmen.

Bitte kopieren Sie die Struktur aus Ebene 1 für jedes ausgewählte Element.

==== _<Infrastrukturelement 1>_

_<Diagramm + Erläuterungen>_

==== _<Infrastrukturelement 2>_

_<Diagramm + Erläuterungen>_

...
==== _<Infrastrukturelement n>_

_<Diagramm + Erläuterungen>_

