receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  influxdb:
    endpoint: "http://influxdb:8086"
    org: "${DOCKER_INFLUXDB_INIT_ORG}"
    bucket: "${DOCKER_INFLUXDB_INIT_BUCKET}"
    token: "${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}"
    metrics_schema: telegraf-prometheus-v1

  logging:

  otlp/jaeger:
    endpoint: http://jaeger:4317
    tls:
      insecure: true

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus, influxdb]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
