name: Adds issues and pull requests to project board

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issues and pull requests to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/orgs/dqualizer/projects/3
          github-token: ${{ secrets.ADD_ISSUES_TO_PROJECTS_PAT }}
